#PBS -l select=1:ncpus=24:mem=64gb,walltime=23:00:00

cd Network_Alignment/code/c/cgraal/

module add anaconda3/5.0.1

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.txt output/random_network/barabasi/barabasi_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.01_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.01.txt output/random_network/barabasi/barabasi_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.03_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.03.txt output/random_network/barabasi/barabasi_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.05_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.05.txt output/random_network/barabasi/barabasi_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.07_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.07.txt output/random_network/barabasi/barabasi_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.09_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.09.txt output/random_network/barabasi/barabasi_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.11_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.11.txt output/random_network/barabasi/barabasi_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.13_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.13.txt output/random_network/barabasi/barabasi_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.15_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.15.txt output/random_network/barabasi/barabasi_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.17_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.17.txt output/random_network/barabasi/barabasi_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.19_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.19.txt output/random_network/barabasi/barabasi_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/barabasi/barabasi_g1.gw gw_dataset/self_under_noise/random_network/barabasi/barabasi_0.21_g2.gw gw_dataset/self_under_noise/random_network/barabasi/sim.txt output/garbage/barabasi_0.21.txt output/random_network/barabasi/barabasi_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.txt output/random_network/homle/homle_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.01_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.01.txt output/random_network/homle/homle_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.03_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.03.txt output/random_network/homle/homle_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.05_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.05.txt output/random_network/homle/homle_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.07_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.07.txt output/random_network/homle/homle_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.09_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.09.txt output/random_network/homle/homle_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.11_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.11.txt output/random_network/homle/homle_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.13_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.13.txt output/random_network/homle/homle_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.15_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.15.txt output/random_network/homle/homle_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.17_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.17.txt output/random_network/homle/homle_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.19_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.19.txt output/random_network/homle/homle_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/random_network/homle/homle_g1.gw gw_dataset/self_under_noise/random_network/homle/homle_0.21_g2.gw gw_dataset/self_under_noise/random_network/homle/sim.txt output/garbage/homle_0.21.txt output/random_network/homle/homle_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.txt output/real_network/bio/bio_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.01_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.01.txt output/real_network/bio/bio_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.03_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.03.txt output/real_network/bio/bio_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.05_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.05.txt output/real_network/bio/bio_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.07_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.07.txt output/real_network/bio/bio_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.09_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.09.txt output/real_network/bio/bio_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.11_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.11.txt output/real_network/bio/bio_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.13_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.13.txt output/real_network/bio/bio_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.15_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.15.txt output/real_network/bio/bio_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.17_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.17.txt output/real_network/bio/bio_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.19_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.19.txt output/real_network/bio/bio_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.21_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.21.txt output/real_network/bio/bio_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.23_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.23.txt output/real_network/bio/bio_0.23.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/bio/bio_g1.gw gw_dataset/self_under_noise/real_network/bio/bio_0.25_g2.gw gw_dataset/self_under_noise/real_network/bio/sim.txt output/garbage/bio_0.25.txt output/real_network/bio/bio_0.25.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.txt output/real_network/econ/econ_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.01_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.01.txt output/real_network/econ/econ_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.03_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.03.txt output/real_network/econ/econ_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.05_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.05.txt output/real_network/econ/econ_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.07_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.07.txt output/real_network/econ/econ_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.09_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.09.txt output/real_network/econ/econ_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.11_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.11.txt output/real_network/econ/econ_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.13_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.13.txt output/real_network/econ/econ_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.15_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.15.txt output/real_network/econ/econ_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.17_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.17.txt output/real_network/econ/econ_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.19_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.19.txt output/real_network/econ/econ_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.21_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.21.txt output/real_network/econ/econ_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.23_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.23.txt output/real_network/econ/econ_0.23.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/econ/econ_g1.gw gw_dataset/self_under_noise/real_network/econ/econ_0.25_g2.gw gw_dataset/self_under_noise/real_network/econ/sim.txt output/garbage/econ_0.25.txt output/real_network/econ/econ_0.25.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.txt output/real_network/newman/newman_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.01_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.01.txt output/real_network/newman/newman_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.03_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.03.txt output/real_network/newman/newman_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.05_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.05.txt output/real_network/newman/newman_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.07_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.07.txt output/real_network/newman/newman_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.09_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.09.txt output/real_network/newman/newman_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.11_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.11.txt output/real_network/newman/newman_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.13_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.13.txt output/real_network/newman/newman_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.15_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.15.txt output/real_network/newman/newman_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.17_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.17.txt output/real_network/newman/newman_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.19_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.19.txt output/real_network/newman/newman_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.21_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.21.txt output/real_network/newman/newman_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.23_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.23.txt output/real_network/newman/newman_0.23.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/newman/newman_g1.gw gw_dataset/self_under_noise/real_network/newman/newman_0.25_g2.gw gw_dataset/self_under_noise/real_network/newman/sim.txt output/garbage/newman_0.25.txt output/real_network/newman/newman_0.25.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.txt output/real_network/router/router_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.01_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.01.txt output/real_network/router/router_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.03_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.03.txt output/real_network/router/router_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.05_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.05.txt output/real_network/router/router_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.07_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.07.txt output/real_network/router/router_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.09_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.09.txt output/real_network/router/router_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.11_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.11.txt output/real_network/router/router_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.13_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.13.txt output/real_network/router/router_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.15_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.15.txt output/real_network/router/router_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.17_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.17.txt output/real_network/router/router_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.19_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.19.txt output/real_network/router/router_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.21_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.21.txt output/real_network/router/router_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.23_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.23.txt output/real_network/router/router_0.23.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/router/router_g1.gw gw_dataset/self_under_noise/real_network/router/router_0.25_g2.gw gw_dataset/self_under_noise/real_network/router/sim.txt output/garbage/router_0.25.txt output/real_network/router/router_0.25.txt