#PBS -l select=1:ncpus=24:mem=64gb,walltime=23:00:00

cd Network_Alignment/code/c/cgraal/

module add anaconda3/5.0.1

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.txt output/real_network/erdos/erdos_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.01_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.01.txt output/real_network/erdos/erdos_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.03_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.03.txt output/real_network/erdos/erdos_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.05_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.05.txt output/real_network/erdos/erdos_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.07_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.07.txt output/real_network/erdos/erdos_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.09_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.09.txt output/real_network/erdos/erdos_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.11_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.11.txt output/real_network/erdos/erdos_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.13_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.13.txt output/real_network/erdos/erdos_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.15_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.15.txt output/real_network/erdos/erdos_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.17_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.17.txt output/real_network/erdos/erdos_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.19_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.19.txt output/real_network/erdos/erdos_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.21_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.21.txt output/real_network/erdos/erdos_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.23_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.23.txt output/real_network/erdos/erdos_0.23.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/erdos/erdos_g1.gw gw_dataset/self_under_noise/real_network/erdos/erdos_0.25_g2.gw gw_dataset/self_under_noise/real_network/erdos/sim.txt output/garbage/erdos_0.25.txt output/real_network/erdos/erdos_0.25.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.txt output/real_network/retweet_2/retweet_2_0.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.01_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.01.txt output/real_network/retweet_2/retweet_2_0.01.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.03_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.03.txt output/real_network/retweet_2/retweet_2_0.03.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.05_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.05.txt output/real_network/retweet_2/retweet_2_0.05.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.07_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.07.txt output/real_network/retweet_2/retweet_2_0.07.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.09_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.09.txt output/real_network/retweet_2/retweet_2_0.09.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.11_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.11.txt output/real_network/retweet_2/retweet_2_0.11.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.13_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.13.txt output/real_network/retweet_2/retweet_2_0.13.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.15_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.15.txt output/real_network/retweet_2/retweet_2_0.15.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.17_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.17.txt output/real_network/retweet_2/retweet_2_0.17.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.19_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.19.txt output/real_network/retweet_2/retweet_2_0.19.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.21_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.21.txt output/real_network/retweet_2/retweet_2_0.21.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.23_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.23.txt output/real_network/retweet_2/retweet_2_0.23.txt

./CGRAAL_unix64 gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_g1.gw gw_dataset/self_under_noise/real_network/retweet_2/retweet_2_0.25_g2.gw gw_dataset/self_under_noise/real_network/retweet_2/sim.txt output/garbage/retweet_2_0.25.txt output/real_network/retweet_2/retweet_2_0.25.txt